#!/usr/bin/env bash
# Generate src/02-fonts-embedded.css with Base64 latin-subset woff2 @font-face rules.
# Reproducible: re-run to regenerate. Source TTFs are OFL (SIL Open Font License).
set -euo pipefail
# Ensure user-installed Python scripts (pyftsubset) are on PATH
export PATH="$HOME/Library/Python/3.9/bin:$PATH"
HERE="$(cd "$(dirname "$0")" && pwd)"          # .../Kuro/src/tools
SRC_DIR="$HERE/.fonts-src"                       # scratch (gitignored)
OUT="$(cd "$HERE/.." && pwd)/02-fonts-embedded.css"
mkdir -p "$SRC_DIR"

# Latin subset (matches Google Fonts "latin" unicode-range)
UNICODES="U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"

RAW="https://raw.githubusercontent.com/google/fonts/main"
FACES=$(cat <<EOF
JetBrains Mono|$RAW/ofl/jetbrainsmono/JetBrainsMono[wght].ttf|400|normal
JetBrains Mono|$RAW/ofl/jetbrainsmono/JetBrainsMono[wght].ttf|500|normal
JetBrains Mono|$RAW/ofl/jetbrainsmono/JetBrainsMono[wght].ttf|600|normal
JetBrains Mono|$RAW/ofl/jetbrainsmono/JetBrainsMono[wght].ttf|700|normal
Space Grotesk|$RAW/ofl/spacegrotesk/SpaceGrotesk[wght].ttf|400|normal
Space Grotesk|$RAW/ofl/spacegrotesk/SpaceGrotesk[wght].ttf|500|normal
Space Grotesk|$RAW/ofl/spacegrotesk/SpaceGrotesk[wght].ttf|600|normal
Space Grotesk|$RAW/ofl/spacegrotesk/SpaceGrotesk[wght].ttf|700|normal
Inter|$RAW/ofl/inter/Inter[opsz,wght].ttf|400|normal
Inter|$RAW/ofl/inter/Inter[opsz,wght].ttf|500|normal
Inter|$RAW/ofl/inter/Inter[opsz,wght].ttf|600|normal
Inter|$RAW/ofl/inter/Inter[opsz,wght].ttf|700|normal
EB Garamond|$RAW/ofl/ebgaramond/EBGaramond[wght].ttf|400|normal
EB Garamond|$RAW/ofl/ebgaramond/EBGaramond[wght].ttf|500|normal
EB Garamond|$RAW/ofl/ebgaramond/EBGaramond[wght].ttf|600|normal
EB Garamond|$RAW/ofl/ebgaramond/EBGaramond-Italic[wght].ttf|400|italic
EB Garamond|$RAW/ofl/ebgaramond/EBGaramond-Italic[wght].ttf|500|italic
EOF
)

{
  echo "/* ── §·fonts  Embedded woff2 (latin subset, SIL OFL) ───────────"
  echo "   Generated by src/tools/make-fonts.sh — do not hand-edit."
  echo "   Families: JetBrains Mono, Space Grotesk, Inter, EB Garamond. */"
  echo ""
} > "$OUT"

while IFS='|' read -r FAM URL WGHT STYLE; do
  [ -z "${FAM:-}" ] && continue
  base="$(echo "${FAM}-${WGHT}-${STYLE}" | tr ' ' '_')"
  # Derive a cache key for the source variable TTF from the URL filename
  varfile="$(basename "$URL")"
  ttf_var="$SRC_DIR/${varfile}"
  ttf_static="$SRC_DIR/${base}-static.ttf"
  woff2="$SRC_DIR/${base}.woff2"

  # 1) Download variable TTF once (curl -g = --globoff disables bracket globbing)
  [ -f "$ttf_var" ] || curl -fsSLg "$URL" -o "$ttf_var"

  # 2) Pin the wght axis to the desired weight to create a static instance
  python3 -m fontTools.varLib.instancer \
    --static \
    -o "$ttf_static" \
    "$ttf_var" "wght=$WGHT" 2>/dev/null

  # 3) Subset to latin unicode range and convert to woff2
  pyftsubset "$ttf_static" \
    --unicodes="$UNICODES" \
    --layout-features='*' \
    --flavor=woff2 \
    --output-file="$woff2"

  b64="$(base64 < "$woff2" | tr -d '\n')"
  {
    echo "@font-face {"
    echo "  font-family: '${FAM}';"
    echo "  font-style: ${STYLE};"
    echo "  font-weight: ${WGHT};"
    echo "  font-display: swap;"
    echo "  src: url(data:font/woff2;base64,${b64}) format('woff2');"
    echo "}"
    echo ""
  } >> "$OUT"
  echo "  ✓ ${FAM} ${WGHT} ${STYLE}"
done <<< "$FACES"

bytes=$(wc -c < "$OUT")
echo "Wrote $OUT — $bytes bytes"
